language: php
dist: trusty

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

before_install:
  - sudo apt-get update
  - sudo apt-get -y install unzip
  - mkdir output/tmp
  - wget -O bin/org.hl7.fhir.validator.jar https://fhir.github.io/latest-ig-publisher/org.hl7.fhir.validator.jar

install:
  - composer install --no-interaction --no-progress --no-suggest
  - ./bin/generate.sh --forceDelete

script:
  - ./vendor/bin/phpunit -d memory_limit=4096M -d precision=14 -d serialize_precision=14 -c phpunit.xml