language: php
dist: xenial
sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

install:
  - composer install --no-interaction --no-progress --no-suggest
  - ./bin/generate.sh --forceDelete

script:
  - ./vendor/bin/phpunit -d memory_limit=4096M -d precision=14 -d serialize_precision=14 -c phpunit.xml